language: node_js
node_js:
  - node

before_install:
  - npm install -g karma-cli

install:
  - npm prune && npm install
  - npm run build
  - npm run build:demo-apps

script:
  - npm test

after_success:
  cat out/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
    - node_modules