language: node_js
node_js:
  - node

before_install:
  - npm install -g karma-cli

install:
  - npm install
  - npm run build

script:
  - npm test

after_success:
  cat out/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js