language: node_js
node_js:
- node

addons:
  sauce_connect: true

before_install:
- npm install -g karma-cli

install:
- npm prune && npm install
- npm run install:demo-apps && npm run setup:demo-apps

before_script:
- npm run build:all
- npm run e2e-server


script:
- npm test
- npm run e2e:ci

after_success: cat out/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
  - node_modules
env:
  global:
  - secure: IegPyce71WauW7bk+31OGODk8qn1U0srF/pBs4GcVFtC3QLRk/D5T2D/7ZCCrsNfFAtHmw8AZhCYiItt3qPEcsQUQIZg/KcfLmV3i4sEShxjx4caK2wLyeGq3hTol+JafUES94QfyezKmpK9C0A17osomYmo7In+bHvxjZwjNLU=
  - secure: VaE4Q7fHi5t6gFYek5hYcveesBkImrs+m0kDE224dMlqoK9Ixhv0Raybx8HGafKtKjOM5fIYHbGENPWK3z8eRZtQhSyIc2rEpy7iYRcf8NF1djD7mxCymsFo7cx7OJmBlqDPsQII/VZfOg30tORoBv+9WQ6pAuggMQM8bCFdsUY=
